export default async function handler(req,res){
if(req.method!=="POST")return res.status(405).json({error:"POST only"});
if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:"AI_NOT_CONFIGURED",message:"OPENAI_API_KEY is not configured on Vercel."});
const {learner,source,evidence=[],role="superuser"}=req.body||{};
if(!learner||!source)return res.status(400).json({error:"learner and source are required"});
const roleRules={learner:"Safe, simple, encouraging. No raw metaphysics, adult interpretations or fixed labels.",parent:"Plain language: what we think, why, evidence, what changed, what to try or avoid.",teacher:"Action only: PRIORITY, DO, DONT, IF STUCK, WATCH FOR, GOAL.",superuser:"Full trace: source, hypothesis, contradiction, evidence, confidence, test, recommendation, outcome and version.",creator:"Full superuser trace plus methodology, source weighting, prompt/rule trace and engine version."};
const instructions="You are the Child Intelligence Engine. Transform structured learner inputs into TESTABLE learner-intelligence hypotheses, never fixed personality claims. Metaphysics is hypothesis-generating only and must never be treated as observed behaviour. Evidence priority: repeated behaviour/outcomes > controlled teaching experiments > academic evidence > teacher observation > psychological evidence > parent/child report > metaphysical prediction. Unknown stays Still discovering. Never invent observations. Separate predicted from observed. Every hypothesis must state: domain, finding, status, source_basis, why, confidence_level, validation_needed, parent_question, child_question, buddy_test, teaching_experiment, success_criteria, contradiction_signal, next_step. Return role_output appropriate for "+role+": "+(roleRules[role]||roleRules.superuser)+". Return JSON only with keys engine_version, learner_id, hypotheses, role_output.";
const payload={model:"gpt-5.6-luna",input:[{role:"system",content:instructions},{role:"user",content:JSON.stringify({learner,source,evidence})}]};
try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":"Bearer "+process.env.OPENAI_API_KEY,"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)return res.status(r.status).json({error:"AI_REQUEST_FAILED",detail:data});const text=(data.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==="output_text").map(x=>x.text).join("");let parsed;try{parsed=JSON.parse(text.replace(/^```json\s*|```$/g,"").trim())}catch{parsed={engine_version:"v0.1",learner_id:learner.id,raw_output:text,hypotheses:[],role_output:{status:"Needs JSON repair"}}}return res.status(200).json(parsed)}catch(e){return res.status(500).json({error:"ENGINE_ERROR",message:e.message})}
}